import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: false,
  minify: false,
  external: [
    'crypto',
    'stream',
    'http',
    'https',
    'http2',
    'events',
    'buffer',
    'assert',
    'url',
    'util',
    'zlib',
    'net',
    'tls',
    'decimal.js',
    'form-data',
    'axios',
    'ws',
    '@aleph-sdk/message',
  ],
  target: 'es2020',
  platform: 'neutral',
  bundle: true,
});
